# Generated by Django 5.0.4 on 2024-04-19 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='available_meals_max',
            field=models.IntegerField(default=0),
        ),
    ]
