# Generated by Django 5.0.4 on 2024-04-22 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_restaurant_available_meals_max'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='is_taken',
            field=models.BooleanField(default=False),
        ),
    ]
