# Generated by Django 5.0.4 on 2024-04-22 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_reservation_is_taken'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='is_taken',
            field=models.BooleanField(default=False),
        ),
    ]
